{'name': 'Rocker Reporting Application',
 'summary': 'Collect data from various datasources to Excel or Powerpoint. Create report and present business graphs with Excel Power Pivot or generate Powerpoint slide decks',
 'description': 'Get data from Odoo & external PostgreSQL, SQLServer, MySQL, MariaDB, ODBC or Oracle databases.',
 'author': 'Antti Kärki',
 'depends': ['base','web'],
 'license': 'AGPL-3',
 'category': 'Extra Tools',
 'version': '13.0.2.0.0',
 'data': [
    'views/database_view.xml',
    'views/archive_view.xml',
     'views/report_view.xml',
     'views/executor_view.xml',
      'data/rocker_data.xml',
     'views/rocker_menu.xml',
     'security/rocker_security.xml',
     'security/ir.model.access.csv',
     'wizard/rocker_popup_wizard.xml',
     'wizard/rocker_about.xml',
 ],
 'application': True,
 'installable': True,
 'images': ['static/description/main_screenshot.png'],

 }
